packages:
  - playground
  - packages/*
allowBuilds:
  '@parcel/watcher': true
  bufferutil: false
  canvas: false
  core-js: false
  edgedriver: false
  esbuild: true
  geckodriver: false
  kerberos: true
  msw: true
  utf-8-validate: false
