package tscodegen

func (g *generator) bytesRuntime() {
	g.line("function runeViewBytes(view: DataView): number[] {")
	g.indent++
	g.line("return Array.from(new Uint8Array(view.buffer, view.byteOffset, view.byteLength));")
	g.indent--
	g.line("}")
	g.line("")
	g.line("function runeDataViewFromBytes(bytes: number[]): DataView {")
	g.indent++
	g.line("const array = new Uint8Array(bytes.map((value) => value & 0xff));")
	g.line("return new DataView(array.buffer.slice(array.byteOffset, array.byteOffset + array.byteLength));")
	g.indent--
	g.line("}")
	g.line("")
	g.line("class RuneBuffer {")
	g.indent++
	g.line("private bytes: number[];")
	g.line("constructor(bytes: number[] = []) { this.bytes = bytes.slice(); }")
	g.line("static fromBytes(value: DataView): RuneBuffer { return new RuneBuffer(runeViewBytes(value)); }")
	g.line("get byteLength(): number { return this.bytes.length; }")
	g.line("clear(): void { this.bytes = []; }")
	g.line("clone(): RuneBuffer { return new RuneBuffer(this.bytes); }")
	g.line("toBytes(): DataView { return runeDataViewFromBytes(this.bytes); }")
	g.line("toInts(): number[] { return this.bytes.slice(); }")
	g.line("append(value: number): RuneBuffer { this.bytes.push(value & 0xff); return this; }")
	g.line("appendInt(value: number): RuneBuffer { this.bytes.push(value & 0xff); return this; }")
	g.line("appendBytes(value: DataView): RuneBuffer { this.bytes.push(...runeViewBytes(value)); return this; }")
	g.line("reader(): RuneReader { return new RuneReader(this.toBytes()); }")
	g.line("writer(): RuneWriter { return new RuneWriter(this.bytes); }")
	g.indent--
	g.line("}")
	g.line("")
	g.line("class RuneReader {")
	g.indent++
	g.line("private view: DataView;")
	g.line("private offset = 0;")
	g.line("private nibble = 0;")
	g.line("constructor(value: DataView) { this.view = new DataView(value.buffer.slice(value.byteOffset, value.byteOffset + value.byteLength)); }")
	g.line("get byteLength(): number { return this.view.byteLength; }")
	g.line("position(): number { return this.offset; }")
	g.line("remaining(): number { return this.view.byteLength - this.offset; }")
	g.line("seek(position: number): number { if (position < 0 || position > this.view.byteLength) throw new RangeError(\"reader offset out of range\"); this.offset = position; this.nibble = 0; return this.offset; }")
	g.line("skip(count: number): number { return this.seek(this.offset + count); }")
	g.line("private align(): void { if (this.nibble === 1) { this.offset++; this.nibble = 0; } if (this.offset > this.view.byteLength) throw new RangeError(\"reader offset out of range\"); }")
	g.line("private take(size: number): number { this.align(); const offset = this.offset; if (offset + size > this.view.byteLength) throw new RangeError(\"reader offset out of range\"); this.offset += size; return offset; }")
	g.line("readBytes(length: number): DataView { const offset = this.take(length); return new DataView(this.view.buffer.slice(this.view.byteOffset + offset, this.view.byteOffset + offset + length)); }")
	g.line("readInt4(): number { if (this.offset >= this.view.byteLength) throw new RangeError(\"reader offset out of range\"); const byte = this.view.getUint8(this.offset); const nibble = this.nibble === 0 ? byte >> 4 : byte & 0xf; if (this.nibble === 0) this.nibble = 1; else { this.nibble = 0; this.offset++; } return nibble >= 8 ? nibble - 16 : nibble; }")
	g.line("readInt8(): number { return this.view.getInt8(this.take(1)); }")
	g.line("readUInt8(): number { return this.view.getUint8(this.take(1)); }")
	g.line("readInt16(littleEndian: boolean): number { return this.view.getInt16(this.take(2), littleEndian); }")
	g.line("readUInt16(littleEndian: boolean): number { return this.view.getUint16(this.take(2), littleEndian); }")
	g.line("readInt(littleEndian: boolean): number { return this.view.getInt32(this.take(4), littleEndian); }")
	g.line("readUInt(littleEndian: boolean): number { return this.view.getUint32(this.take(4), littleEndian); }")
	g.line("readInt64(littleEndian: boolean): bigint { return this.view.getBigInt64(this.take(8), littleEndian); }")
	g.line("readUInt64(littleEndian: boolean): bigint { return this.view.getBigUint64(this.take(8), littleEndian); }")
	g.line("readFloat(littleEndian: boolean): number { return this.view.getFloat32(this.take(4), littleEndian); }")
	g.line("readDouble(littleEndian: boolean): number { return this.view.getFloat64(this.take(8), littleEndian); }")
	g.indent--
	g.line("}")
	g.line("")
	g.line("class RuneWriter {")
	g.indent++
	g.line("private bytes: number[];")
	g.line("private nibble = 0;")
	g.line("constructor(bytesOrCapacity: number[] | number = []) { this.bytes = Array.isArray(bytesOrCapacity) ? bytesOrCapacity.slice() : []; }")
	g.line("get byteLength(): number { return this.bytes.length; }")
	g.line("position(): number { return this.bytes.length; }")
	g.line("clear(): void { this.bytes = []; this.nibble = 0; }")
	g.line("toBytes(): DataView { return runeDataViewFromBytes(this.bytes); }")
	g.line("toInts(): number[] { return this.bytes.slice(); }")
	g.line("private align(): void { this.nibble = 0; }")
	g.line("private writeView(size: number, fill: (view: DataView) => void): RuneWriter { this.align(); const view = new DataView(new ArrayBuffer(size)); fill(view); this.bytes.push(...runeViewBytes(view)); return this; }")
	g.line("writeBytes(value: DataView): RuneWriter { this.align(); this.bytes.push(...runeViewBytes(value)); return this; }")
	g.line("writeInt4(value: number): RuneWriter { const nibble = value & 0xf; if (this.nibble === 0) { this.bytes.push(nibble << 4); this.nibble = 1; } else { this.bytes[this.bytes.length - 1] = (this.bytes[this.bytes.length - 1] & 0xf0) | nibble; this.nibble = 0; } return this; }")
	g.line("writeInt8(value: number): RuneWriter { return this.writeView(1, (view) => view.setInt8(0, value)); }")
	g.line("writeUInt8(value: number): RuneWriter { return this.writeView(1, (view) => view.setUint8(0, value)); }")
	g.line("writeInt16(value: number, littleEndian: boolean): RuneWriter { return this.writeView(2, (view) => view.setInt16(0, value, littleEndian)); }")
	g.line("writeUInt16(value: number, littleEndian: boolean): RuneWriter { return this.writeView(2, (view) => view.setUint16(0, value, littleEndian)); }")
	g.line("writeInt(value: number, littleEndian: boolean): RuneWriter { return this.writeView(4, (view) => view.setInt32(0, value, littleEndian)); }")
	g.line("writeUInt(value: number, littleEndian: boolean): RuneWriter { return this.writeView(4, (view) => view.setUint32(0, value, littleEndian)); }")
	g.line("writeInt64(value: bigint, littleEndian: boolean): RuneWriter { return this.writeView(8, (view) => view.setBigInt64(0, value, littleEndian)); }")
	g.line("writeUInt64(value: bigint, littleEndian: boolean): RuneWriter { return this.writeView(8, (view) => view.setBigUint64(0, value, littleEndian)); }")
	g.line("writeFloat(value: number, littleEndian: boolean): RuneWriter { return this.writeView(4, (view) => view.setFloat32(0, value, littleEndian)); }")
	g.line("writeDouble(value: number, littleEndian: boolean): RuneWriter { return this.writeView(8, (view) => view.setFloat64(0, value, littleEndian)); }")
	g.indent--
	g.line("}")
}
