// gen-dom-stub emits a compact Rune data file (selfhost/compiler/dom_types.rn)
// describing the DOM surface the self-hosted checker needs for React-like XML
// event typing:
//
//	DOM_EVENT_NAMES / DOM_EVENT_TYPE_NAMES
//	                   — event listener name -> DOM event interface (derived from
//	                     GlobalEventHandlersEventMap, which HTMLElementEventMap extends)
//	DOM_TAG_NAMES / DOM_TAG_ELEMENT_TYPES
//	                   — XML tag name -> element interface (derived from
//	                     HTMLElementTagNameMap)
//	DOM_STRUCT_NAMES / DOM_STRUCT_MEMBERS
//	                   — flattened member shapes of event interfaces + form-control
//	                     element interfaces (so e.target.value resolves on <input>,
//	                     <textarea>, <select>, <button>, <option>)
//
// Everything is derived from a TypeScript lib.dom.d.ts parse — no hand table —
// so edition drift in the declaration file is picked up automatically.
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/oboard/rune-lang/internal/tsdecl"
)

func main() {
	lib := flag.String("lib", defaultLib(), "path to lib.dom.d.ts")
	out := flag.String("out", "selfhost/compiler/dom_types.rn", "output Rune file")
	flag.Parse()

	dom, err := tsdecl.LoadFile(*lib)
	if err != nil {
		fmt.Fprintln(os.Stderr, "load:", err)
		os.Exit(1)
	}
	flat := tsdecl.FlattenAll(dom)

	b := strings.Builder{}
	b.WriteString("// Code generated by internal/tsdecl/cmd/gen-dom-stub — DO NOT EDIT.\n")
	b.WriteString("// Ambient DOM event surface derived from TypeScript's lib.dom.d.ts.\n\n")

	// ---- Event name -> event interface -----------------------------------
	// Parallel arrays (name list + type list) so the self-hosted checker scans
	// linearly without needing nullable map indexing.
	events := normalizedEventMap(flat["HTMLElementEventMap"])
	names := make([]string, 0, len(events))
	for n := range events {
		names = append(names, n)
	}
	sort.Strings(names)

	b.WriteString("DOM_EVENT_NAMES := [\n")
	for i, n := range names {
		fmt.Fprintf(&b, "  %q", n)
		if i < len(names)-1 {
			b.WriteString(", ")
		}
		b.WriteString("\n")
	}
	b.WriteString("]\n\n")

	b.WriteString("DOM_EVENT_TYPE_NAMES := [\n")
	for i, n := range names {
		fmt.Fprintf(&b, "  %q", events[n])
		if i < len(names)-1 {
			b.WriteString(", ")
		}
		b.WriteString("\n")
	}
	b.WriteString("]\n\n")

	// ---- Tag name -> element interface ----------------------------------
	// Parallel arrays again; keys are unquoted tag names ("div", "input", ...).
	tags := normalizedTagMap(flat["HTMLElementTagNameMap"])
	tagNames := make([]string, 0, len(tags))
	for n := range tags {
		tagNames = append(tagNames, n)
	}
	sort.Strings(tagNames)

	b.WriteString("DOM_TAG_NAMES := [\n")
	for i, n := range tagNames {
		fmt.Fprintf(&b, "  %q", n)
		if i < len(tagNames)-1 {
			b.WriteString(", ")
		}
		b.WriteString("\n")
	}
	b.WriteString("]\n\n")

	b.WriteString("DOM_TAG_ELEMENT_TYPES := [\n")
	for i, n := range tagNames {
		fmt.Fprintf(&b, "  %q", tags[n])
		if i < len(tagNames)-1 {
			b.WriteString(", ")
		}
		b.WriteString("\n")
	}
	b.WriteString("]\n\n")

	// ---- Event interface member shapes -----------------------------------
	// Each event interface is shipped in its flattened view (bases merged),
	// plus the structural targets (EventTarget, Node) that handler member
	// access flows through, plus the form-control element interfaces whose
	// `target` is narrowed when the handler is attached to that tag.
	structNames := eventSurfaceNames(flat, events, tags)

	b.WriteString("DOM_STRUCT_NAMES := [\n")
	for i, name := range structNames {
		fmt.Fprintf(&b, "  %q", name)
		if i < len(structNames)-1 {
			b.WriteString(", ")
		}
		b.WriteString("\n")
	}
	b.WriteString("]\n\n")

	b.WriteString("DOM_STRUCT_MEMBERS := [\n")
	for i, name := range structNames {
		rows := memberRows(flat[name])
		b.WriteString("  [\n")
		b.WriteString(strings.Join(rows, ",\n"))
		b.WriteString("\n  ]")
		if i < len(structNames)-1 {
			b.WriteString(", ")
		}
		b.WriteString("\n")
	}
	b.WriteString("]\n")

	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write:", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wrote %s (%d bytes, %d events, %d tags, %d structs)\n",
		*out, len(b.String()), len(names), len(tagNames), len(structNames))
}

// normalizedTagMap reads HTMLElementTagNameMap and returns tag name (unquoted)
// -> element interface type name.
func normalizedTagMap(m *tsdecl.Flattened) map[string]string {
	out := map[string]string{}
	if m == nil {
		return out
	}
	for _, mem := range m.Members {
		key := strings.Trim(mem.Name, `"`)
		if key == "" {
			continue
		}
		if name := refTypeName(mem.Type); name != "Event" {
			out[key] = name
		}
	}
	return out
}

func defaultLib() string {
	candidates := []string{
		"/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.dom.d.ts",
		"node_modules/typescript/lib/lib.dom.d.ts",
		"lib.dom.d.ts",
	}
	for _, p := range candidates {
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	return candidates[0]
}

// normalizedEventMap reads the flattened event-map interface and returns
// event name (unquoted) -> event interface type name.
func normalizedEventMap(m *tsdecl.Flattened) map[string]string {
	out := map[string]string{}
	if m == nil {
		return out
	}
	for _, mem := range m.Members {
		key := strings.Trim(mem.Name, `"`)
		if key == "" {
			continue
		}
		out[key] = refTypeName(mem.Type)
	}
	return out
}

// refTypeName extracts a plain interface name from an event-map entry's type
// (a bare `Ref` in lib.dom.d.ts, e.g. KeyboardEvent).
func refTypeName(t tsdecl.Type) string {
	if r, ok := t.(tsdecl.Ref); ok {
		return r.Name
	}
	return "Event"
}

// eventSurfaceNames returns the sorted set of interfaces to ship: each event
// interface (already flattening its own base members), the structural types
// field access flows through (EventTarget, Node), and the form-control element
// interfaces that a handler's `target` is narrowed to (so e.target.value works
// on <input>, <textarea>, <select>, <button>, <option>).
func eventSurfaceNames(flat map[string]*tsdecl.Flattened, events map[string]string, tags map[string]string) []string {
	seen := map[string]bool{}
	for _, evt := range events {
		seen[evt] = true
	}
	// e.target / e.currentTarget resolve to EventTarget or Node.
	for _, extra := range []string{"EventTarget", "Node"} {
		seen[extra] = true
	}
	// Form-control elements whose .value is the React-parity target narrow.
	for _, elem := range []string{
		"HTMLInputElement",
		"HTMLTextAreaElement",
		"HTMLSelectElement",
		"HTMLButtonElement",
		"HTMLOptionElement",
	} {
		seen[elem] = true
	}
	// Only keep names actually present in the flat view.
	for n := range seen {
		if flat[n] == nil {
			delete(seen, n)
		}
	}
	names := make([]string, 0, len(seen))
	for n := range seen {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

// memberRows renders one interface's flattened members as
// "name: Type" (fields) or "name(P1, P2): Ret" (methods).
func memberRows(f *tsdecl.Flattened) []string {
	if f == nil {
		return nil
	}
	rows := make([]string, 0, len(f.Members))
	for _, m := range f.Members {
		t := typeName(m.Type)
		if m.IsMethod {
			params := make([]string, 0, len(m.Params))
			for _, p := range m.Params {
				params = append(params, typeName(p.Type))
			}
			rows = append(rows, fmt.Sprintf("    %q", m.Name+"("+strings.Join(params, ", ")+"): "+t))
		} else {
			rows = append(rows, fmt.Sprintf("    %q", m.Name+":"+t))
		}
	}
	return rows
}

// typeName maps a tsdecl type to the Rune type name string the self-hosted
// checker understands. Unknown shapes degrade to "Dynamic" so lookups never
// panic and errors stay contained.
func typeName(t tsdecl.Type) string {
	switch v := t.(type) {
	case tsdecl.Any:
		return "Dynamic"
	case tsdecl.Primitive:
		switch v.Name {
		case "String", "Bool", "BigInt", "Void", "Null", "Object":
			return v.Name
		case "Boolean":
			return "Bool"
		}
		return "Dynamic"
	case tsdecl.Literal:
		return "String"
	case tsdecl.Ref:
		return v.Name
	case tsdecl.Array:
		return "Array[" + typeName(v.Elem) + "]"
	case tsdecl.Union:
		return unionTypeName(v.Options)
	case tsdecl.Intersect:
		for _, o := range v.Options {
			if n := typeName(o); n != "Dynamic" {
				return n
			}
		}
		return "Dynamic"
	case tsdecl.Callback:
		return "Dynamic"
	}
	return "Dynamic"
}

func unionTypeName(opts []tsdecl.Type) string {
	var survivors []string
	for _, o := range opts {
		n := typeName(o)
		if n == "Null" || n == "Void" {
			continue
		}
		survivors = append(survivors, n)
	}
	if len(survivors) == 1 {
		return survivors[0]
	}
	return "Dynamic"
}