package selfhostrunner

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/oboard/rune-lang/internal/compiler"
)

func TestRunMainIR(t *testing.T) {
	prog, diags := compiler.AnalyzeSource("main_ir.rn", `main() => {
  @io.println("hello", 42)
}`)
	if len(diags) > 0 {
		t.Fatalf("AnalyzeSource diagnostics = %v", diags)
	}
	result := RunMainIR(prog.IR)
	if result.Err != nil {
		t.Fatalf("RunMainIR error = %v, output = %q", result.Err, result.Output)
	}
	if result.Output != "hello 42\n" {
		t.Fatalf("RunMainIR output = %q, want %q", result.Output, "hello 42\n")
	}
}

func TestRunCoreModuleTestsIR(t *testing.T) {
	runSelfhostIRTests(t, "core_modules.rn", []string{
		"iter module helpers",
		"stringbuffer module helpers",
		"path module helpers",
		"process module helpers",
		"io input helpers",
	})
	runSelfhostIRTests(t, "types_string.rn", []string{
		"string length and emptiness",
		"string concat and containment",
		"string indexing and slicing",
		"string prefix and suffix",
		"string index search",
		"string case conversion",
		"string trimming",
		"string repeat",
		"string replace variants",
		"string split",
		"string comparison",
		"template strings",
	})
	runSelfhostIRTests(t, "types_array.rn", []string{
		"array literals and index",
		"array spread literal",
		"array push and at",
		"array mutation and slices",
		"array each",
		"array map",
		"array reduce and folds",
		"nested arrays",
		"array nullable elements",
	})
	runSelfhostIRTests(t, "types_map.rn", []string{
		"map core methods",
		"map literal string keys",
		"map literal integer keys",
		"map literal bool and float keys",
		"set core methods",
	})
	runSelfhostIRTests(t, "types_bytes.rn", []string{
		"bitwise operators on Int",
		"bitwise operators on widened integers",
		"bitwise operators on BigInt",
		"widened numeric conversions",
		"bytes int4 and byte operations",
		"bytes numeric DataView operations",
		"bytes fromInts clone and slice",
		"buffer module append and export",
		"reader module reads sequential values",
		"reader seek skip and buffer helpers",
	})
	runSelfhostIRTests(t, "types_regex.rn", []string{
		"regex literal metadata and test",
		"regex exec captures and miss",
		"regex global match and matchAll",
		"regex replace search split and constructor",
		"regex stateful lastIndex and escape",
	})
	runSelfhostIRTests(t, "json.rn", []string{
		"json stringify anonymous object",
		"json macros configure struct fields",
		"json parse uses FromJson generated by macro",
		"json generated FromJson method delegates to parse",
	})
	runSelfhostIRTests(t, "types_bool.rn", []string{
		"bool literals and equality",
		"bool unary not",
		"bool conjunction truth table",
		"bool disjunction truth table",
		"bool and short circuits false left",
		"bool and evaluates true left",
		"bool or short circuits true left",
		"bool or evaluates false left",
		"bool receiver methods",
		"bool comparison expressions",
		"bool composed expressions",
	})
	runSelfhostIRTests(t, "types_char.rn", []string{
		"char literals and methods",
		"string indexing returns char",
		"char comparison and patterns",
		"char map and set keys",
	})
	runSelfhostIRTests(t, "types_enum.rn", []string{
		"enum members and comparison",
		"enum typed parameter and match",
		"enum in struct fields",
		"enum type name can be shadowed by local binding",
	})
	runSelfhostIRTests(t, "types_nullable.rn", []string{
		"null literal and comparison",
		"nullable int parameter and return",
		"nullable double parameter and return",
		"nullable bigint parameter and return",
		"nullable string parameter and return",
		"nullable bool parameter and return",
		"array of nullable int",
		"array of nullable doubles",
		"array of nullable bigints",
		"array of nullable strings",
		"array of nullable bools",
		"nullable base types stay separate",
	})
	runSelfhostIRTests(t, "types_numeric.rn", []string{
		"int literals",
		"int arithmetic",
		"int comparison",
		"int negation",
		"double literals",
		"double arithmetic",
		"double comparison",
		"double negation",
		"bigint literals",
		"bigint arithmetic",
		"bigint comparison",
		"bigint negation",
		"numeric module conversions",
	})
	runSelfhostIRTests(t, "types_object_symbol.rn", []string{
		"named object fields and methods",
		"nested record like named objects",
		"anonymous object fields and methods",
		"object typed parameter accepts object values",
		"record like anonymous object inference",
	})
	runSelfhostIRTests(t, "types_pattern.rn", []string{
		"moonbit-style array and as patterns",
		"moonbit-style string and open range patterns",
		"moonbit-style constructor payload patterns",
		"moonbit-style string spread array patterns",
		"moonbit-style optional map key patterns",
		"moonbit-style bitstring patterns",
		"moonbit-style json patterns",
	})
	runSelfhostIRTests(t, "types_symbol.rn", []string{
		"symbol constructors and descriptions",
		"symbol registry keys",
	})
	runSelfhostIRTests(t, "types_ternary.rn", []string{
		"ternary expressions",
		"ternary short circuits",
		"ternary void branches",
		"conditional expression without else",
	})
	runSelfhostIRTests(t, "cli.rn", []string{
		"cli parses flags options and arguments",
		"cli supports defaults rest args and short values",
		"cli validates required values and help",
	})
	runSelfhostIRTests(t, "compress.rn", []string{
		"compress codec routine signatures",
	})
	runSelfhostIRTests(t, "data_types.rn", []string{
		"numeric and nullable",
		"bool and string",
	})
	runSelfhostIRTests(t, "private.rn", []string{
		"private declarations work inside source",
	})
	runSelfhostIRTests(t, "imports.rn", []string{
		"rune file imports",
	})
	runSelfhostIRTests(t, "compiler_bootstrap.rn", []string{
		"selfhost compiler emits typescript functions",
		"selfhost compiler emits go functions",
		"selfhost compiler emits moonbit functions",
		"selfhost compiler emits declarations and println",
		"selfhost compiler emits go payload enums",
		"selfhost compiler emits result unwrap helpers",
		"selfhost compiler reports parser errors",
	})
}

func TestRunSelfhostBootstrapTestsIR(t *testing.T) {
	runSelfhostIRAllTests(t, "lexer_bootstrap.rn")
	runSelfhostIRAllTests(t, "parser_bootstrap.rn")
	runSelfhostIRAllTests(t, "ir_bootstrap.rn")
	runSelfhostIRAllTests(t, "cli_bootstrap.rn")
	runSelfhostIRAllTests(t, "interpreter_bootstrap.rn")
}

func runSelfhostIRTests(t *testing.T, file string, names []string) {
	t.Helper()
	path := filepath.Join("..", "..", "tests", file)
	prog, diags := compiler.AnalyzeFile(path)
	if len(diags) > 0 {
		t.Fatalf("AnalyzeFile(%s) diagnostics = %v", path, diags)
	}
	for _, name := range names {
		result := RunTestIR(prog.IR, name)
		if result.Err != nil {
			t.Fatalf("RunTestIR(%s %q) error = %v, output = %q", file, name, result.Err, result.Output)
		}
	}
}

func runSelfhostIRAllTests(t *testing.T, file string) {
	t.Helper()
	path := filepath.Join("..", "..", "tests", file)
	prog, diags := compiler.AnalyzeFile(path)
	if len(diags) > 0 {
		t.Fatalf("AnalyzeFile(%s) diagnostics = %v", path, diags)
	}
	for _, test := range prog.IR.Tests {
		result := RunTestIR(prog.IR, test.Name)
		if result.Err != nil {
			t.Fatalf("RunTestIR(%s %q) error = %v, output = %q", file, test.Name, result.Err, result.Output)
		}
	}
}

func TestSelfhostCompilerTargetOutputsTypecheck(t *testing.T) {
	resultProgram := `Result[T, E]: {
  Ok(value: T)
  Err(error: E)
}

read() -> Result[Int, String] => Ok(41)

main() -> Int => {
  value := read()?
  value + 1
}
`
	checkSelfhostCompiledGo(t, resultProgram)
	if _, err := exec.LookPath("tsc"); err == nil {
		checkSelfhostCompiledTypeScript(t, resultProgram)
	} else {
		t.Log("tsc not found; skipping TypeScript toolchain check")
	}
	if _, err := exec.LookPath("moon"); err == nil {
		checkSelfhostCompiledMoonBit(t, resultProgram)
	} else {
		t.Log("moon not found; skipping MoonBit toolchain check")
	}

	declarationProgram := `Status: {
  Ready = 1
}
User: {
  name: String
}
main() => {
  user := User { name: "Rune" }
  @io.println(user.name, Status.Ready)
}
`
	checkSelfhostCompiledGo(t, declarationProgram)
	if _, err := exec.LookPath("moon"); err == nil {
		checkSelfhostCompiledMoonBit(t, declarationProgram)
	}

	coreMethodProgram := `main() => {
  values := [1, 2, 3]
  word := "rune"
  middle := values.slice(1, 3)
  letters := word.slice(1, 3)
  @io.println(values.length(), values.isEmpty(), values.at(1), middle.length(), middle.at(0), word.length(), word.isEmpty(), word.at(0), letters)
}
`
	checkSelfhostCompiledGo(t, coreMethodProgram)
	if _, err := exec.LookPath("tsc"); err == nil {
		checkSelfhostCompiledTypeScript(t, coreMethodProgram)
	}
	if _, err := exec.LookPath("moon"); err == nil {
		checkSelfhostCompiledMoonBit(t, coreMethodProgram)
	}

	coreModuleProgram := `main() => {
  absolute := @path.isAbsolute("/tmp/rune")
  base := @path.basename("src/lexer.rn")
  ext := @path.extname("src/lexer.rn")
  dir := @path.dirname("src/lexer.rn")
  joined := @path.join(["src", "parser", "..", "lexer.rn"])
  normalized := @path.normalize("/src/./parser/../lexer.rn")
  resolved := @path.resolve(["src", "parser", "..", "lexer.rn"])
  relative := @path.relative("src/parser", "src/lexer/token.rn")
  joinedParts := @path.joinParts(["src", "", "lexer.rn"], 0, "")
  appended := @path.appendPathPart("src", "lexer.rn")
  normalizedParts := @path.normalizeParts(["src", ".", "parser", "..", "lexer.rn"], 0, false, [])
  normalizePart := @path.normalizePart(["."], 0, false, [])
  normalizeParent := @path.normalizeParent([".."], 0, false, [])
  normalizePop := @path.normalizePop([".."], 0, false, ["src"])
  normalizePush := @path.normalizePush(["lexer.rn"], 0, false, ["src"], "lexer.rn")
  pathParts := @path.pathParts("/src/lexer.rn")
  collectedParts := @path.collectPathParts(["", "src", "lexer.rn"], 0, [])
  collectedPart := @path.collectPathPart(["src"], 0, [])
  relativeFromParts := @path.relativeFromParts(["src", "parser"], ["src", "lexer", "token.rn"], 0)
  relativeTail := @path.relativeTail(["src", "parser"], ["src", "lexer"], 1, 1, "")
  platform := @process.platform()
  cwd := @process.cwd()
  missing := @process.env("__RUNE_SELFHOST_MISSING__")
  args := @process.argv()
  int4 := @int4.toInt(@int4.fromInt(15))
  int8 := @int8.toInt(@int8.fromInt(130))
  int16 := @int16.toInt(@int16.fromInt(65535))
  int64 := @int64.toInt(@int64.fromInt(123456))
  uint := @uint.toInt(@uint.fromInt(123456))
  uint8 := @uint8.toInt(@uint8.fromInt(255))
  uint16 := @uint16.toInt(@uint16.fromInt(65535))
  uint64 := @uint64.toInt(@uint64.fromInt(123456))
  float := @float.toDouble(@float.fromDouble(1.5))
  number := @int.toString(42)
  double := @int.toDouble(7)
  bigint := @int.toBigInt(5)
  bigintFromInt := @bigint.fromInt(6)
  bigintText := @bigint.toString(6n)
  bigintDouble := @bigint.toDouble(7n)
  trunc := @double.trunc(7.9)
  floor := @double.floor(7.9)
  ceil := @double.ceil(7.1)
  round := @double.round(7.6)
  @io.println(absolute, base, ext, dir, joined, normalized, resolved, relative, joinedParts, appended, normalizedParts.length(), normalizedParts[0], normalizedParts[1], normalizePart.length(), normalizeParent[0], normalizePop.length(), normalizePush.length(), normalizePush[1], pathParts.length(), pathParts[0], pathParts[1], collectedParts.length(), collectedParts[0], collectedParts[1], collectedPart.length(), collectedPart[0], relativeFromParts, relativeTail, platform.isEmpty(), cwd.isEmpty(), missing == null, args.length(), int4, int8, int16, int64, uint, uint8, uint16, uint64, float, number, double, bigint, bigintFromInt, bigintText, bigintDouble, trunc, floor, ceil, round)
}
`
	checkSelfhostCompiledGo(t, coreModuleProgram)
	checkSelfhostCompiledGoOutput(t, coreModuleProgram, "true lexer.rn .rn src src/lexer.rn /src/lexer.rn src/lexer.rn ../lexer/token.rn src/lexer.rn src/lexer.rn 2 src lexer.rn 0 .. 0 2 lexer.rn 2 src lexer.rn 2 src lexer.rn 1 src ../lexer/token.rn ../lexer false false true 0 -1 -126 -1 123456 123456 255 65535 123456 1.5 42 7 5 6 6 7 7 7 8 8\n")
	if _, err := exec.LookPath("tsc"); err == nil {
		checkSelfhostCompiledTypeScript(t, coreModuleProgram)
		if _, err := exec.LookPath("node"); err == nil {
			checkSelfhostCompiledTypeScriptOutput(t, coreModuleProgram, "true lexer.rn .rn src src/lexer.rn /src/lexer.rn src/lexer.rn ../lexer/token.rn src/lexer.rn src/lexer.rn 2 src lexer.rn 0 .. 0 2 lexer.rn 2 src lexer.rn 2 src lexer.rn 1 src ../lexer/token.rn ../lexer false false true 0 -1 -126 -1 123456 123456 255 65535 123456 1.5 42 7 5n 6n 6 7 7 7 8 8\n")
		} else {
			t.Log("node not found; skipping TypeScript runtime check")
		}
	}
	if _, err := exec.LookPath("moon"); err == nil {
		checkSelfhostCompiledMoonBit(t, coreModuleProgram)
		checkSelfhostCompiledMoonBitOutput(t, coreModuleProgram, "true lexer.rn .rn src src/lexer.rn /src/lexer.rn src/lexer.rn ../lexer/token.rn src/lexer.rn src/lexer.rn 2 src lexer.rn 0 .. 0 2 lexer.rn 2 src lexer.rn 2 src lexer.rn 1 src ../lexer/token.rn ../lexer false false true 0 -1 -126 -1 123456 123456 255 65535 123456 1.5 42 7 5 6 6 7 7 7 8 8\n")
	}
}

func checkSelfhostCompiledGo(t *testing.T, source string) {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "main.go")
	output := selfhostCompileOutput(t, "compileGo", source)
	if err := os.WriteFile(path, []byte(output), 0o644); err != nil {
		t.Fatalf("WriteFile(%s) error = %v", path, err)
	}
	cmd := exec.Command("go", "test", path)
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go test failed: %v\n%s\nsource:\n%s", err, out, output)
	}
}

func checkSelfhostCompiledGoOutput(t *testing.T, source string, want string) {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "main.go")
	output := selfhostCompileOutput(t, "compileGo", source)
	if err := os.WriteFile(path, []byte(output), 0o644); err != nil {
		t.Fatalf("WriteFile(%s) error = %v", path, err)
	}
	cmd := exec.Command("go", "run", path)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("go run failed: %v\n%s\nsource:\n%s", err, out, output)
	}
	if string(out) != want {
		t.Fatalf("go run output = %q, want %q\nsource:\n%s", out, want, output)
	}
}

func checkSelfhostCompiledTypeScript(t *testing.T, source string) {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "main.ts")
	output := selfhostCompileOutput(t, "compileTypeScript", source)
	if err := os.WriteFile(path, []byte(output), 0o644); err != nil {
		t.Fatalf("WriteFile(%s) error = %v", path, err)
	}
	cmd := exec.Command("tsc", "--target", "ES2020", "--module", "ES2020", "--noEmit", "--strict", path)
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("tsc failed: %v\n%s\nsource:\n%s", err, out, output)
	}
}

func checkSelfhostCompiledTypeScriptOutput(t *testing.T, source string, want string) {
	t.Helper()
	dir := t.TempDir()
	mainPath := filepath.Join(dir, "main.ts")
	output := selfhostCompileOutput(t, "compileTypeScript", source)
	if err := os.WriteFile(mainPath, []byte(output+"\n__main();\n"), 0o644); err != nil {
		t.Fatalf("WriteFile(%s) error = %v", mainPath, err)
	}
	if err := os.WriteFile(filepath.Join(dir, "package.json"), []byte("{\"type\":\"module\"}\n"), 0o644); err != nil {
		t.Fatalf("WriteFile package.json error = %v", err)
	}
	cmd := exec.Command("tsc", "--target", "ES2020", "--module", "NodeNext", "--moduleResolution", "NodeNext", "--strict", "main.ts")
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("tsc runtime build failed: %v\n%s\nsource:\n%s", err, out, output)
	}
	run := exec.Command("node", filepath.Join(dir, "main.js"))
	out, err := run.CombinedOutput()
	if err != nil {
		t.Fatalf("node run failed: %v\n%s\nsource:\n%s", err, out, output)
	}
	if string(out) != want {
		t.Fatalf("node output = %q, want %q\nsource:\n%s", out, want, output)
	}
}

func checkSelfhostCompiledMoonBit(t *testing.T, source string) {
	t.Helper()
	dir := t.TempDir()
	output := selfhostCompileOutput(t, "compileMoonBit", source)
	writeSelfhostMoonBitPackage(t, dir, output)
	cmd := exec.Command("moon", "check", "--target", "native")
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("moon check failed: %v\n%s\nsource:\n%s", err, out, output)
	}
}

func checkSelfhostCompiledMoonBitOutput(t *testing.T, source string, want string) {
	t.Helper()
	dir := t.TempDir()
	output := selfhostCompileOutput(t, "compileMoonBit", source)
	writeSelfhostMoonBitPackage(t, dir, output)
	cmd := exec.Command("moon", "run", "--target", "native", ".")
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("moon run failed: %v\n%s\nsource:\n%s", err, out, output)
	}
	if string(out) != want {
		t.Fatalf("moon run output = %q, want %q\nsource:\n%s", out, want, output)
	}
}

func writeSelfhostMoonBitPackage(t *testing.T, dir string, output string) {
	t.Helper()
	files := map[string]string{
		"main.mbt": output,
		"moon.mod": "name = \"oboard/rune_selfhost_target\"\n",
		"moon.pkg": strings.Join([]string{
			"import {",
			"  \"moonbitlang/core/env\",",
			"  \"moonbitlang/core/string\"",
			"}",
			"",
			"warnings = \"-1-7-23-67\"",
			"",
			"options(",
			"  \"is-main\": true,",
			")",
			"",
		}, "\n"),
	}
	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatalf("WriteFile(%s) error = %v", path, err)
		}
	}
}

func selfhostCompileOutput(t *testing.T, function string, source string) string {
	t.Helper()
	compilerPath := filepath.Join(repoRootForTest(t), "selfhost", "compiler", "compiler.rn")
	program := "@" + quoteRuneString(compilerPath) + "\n\nmain() => {\n  source := `" + source + "`\n  result := " + function + "(source)\n  @io.println(result.output)\n}\n"
	prog, diags := compiler.AnalyzeSource("selfhost_compile_output.rn", program)
	if len(diags) > 0 {
		t.Fatalf("AnalyzeSource diagnostics = %v\nprogram:\n%s", diags, program)
	}
	result := RunMainIR(prog.IR)
	if result.Err != nil {
		t.Fatalf("RunMainIR error = %v, output = %q", result.Err, result.Output)
	}
	return result.Output
}

func repoRootForTest(t *testing.T) string {
	t.Helper()
	root, err := repoRoot()
	if err != nil {
		t.Fatalf("repoRoot error = %v", err)
	}
	return root
}

func quoteRuneString(value string) string {
	return "\"" + strings.ReplaceAll(strings.ReplaceAll(value, "\\", "\\\\"), "\"", "\\\"") + "\""
}

func TestCleanupSelfhostDriverCache(t *testing.T) {
	dir := t.TempDir()
	keep := filepath.Join(dir, "driver-current")
	files := []string{
		"driver-current",
		"driver-old",
		"driver-old.go",
		"driver-old.tmp",
		"driver.go",
		"notes.txt",
	}
	for _, name := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(name), 0o644); err != nil {
			t.Fatalf("WriteFile(%s) error = %v", name, err)
		}
	}

	cleanupSelfhostDriverCache(dir, keep)

	for _, name := range []string{"driver-current", "driver-old.go", "driver-old.tmp", "driver.go", "notes.txt"} {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			t.Fatalf("expected %s to remain: %v", name, err)
		}
	}
	for _, name := range []string{"driver-old"} {
		if _, err := os.Stat(filepath.Join(dir, name)); !os.IsNotExist(err) {
			t.Fatalf("expected %s to be removed, stat err = %v", name, err)
		}
	}
}

func TestSelfhostGoBuildCacheIsTemporary(t *testing.T) {
	dir := t.TempDir()
	goCacheDir, cleanup, err := selfhostGoBuildCache(dir)
	if err != nil {
		t.Fatalf("selfhostGoBuildCache error = %v", err)
	}
	if err := os.WriteFile(filepath.Join(goCacheDir, "entry"), []byte("cache"), 0o644); err != nil {
		t.Fatalf("WriteFile cache entry error = %v", err)
	}

	cleanup()

	if _, err := os.Stat(goCacheDir); !os.IsNotExist(err) {
		t.Fatalf("expected temporary Go build cache to be removed, stat err = %v", err)
	}
}

func TestSelfhostDriverCacheKeyChangesWithInputs(t *testing.T) {
	root := t.TempDir()
	for _, dir := range []string{"cmd/rune", "core", "internal/selfhostrunner", "selfhost/interpreter"} {
		if err := os.MkdirAll(filepath.Join(root, dir), 0o755); err != nil {
			t.Fatalf("MkdirAll(%s) error = %v", dir, err)
		}
	}
	files := map[string]string{
		"go.mod":                            "module test\n",
		"go.sum":                            "",
		"cmd/rune/main.go":                  "package main\n",
		"core/string.rn":                    "value() => 1\n",
		"internal/selfhostrunner/a.go":      "package selfhostrunner\n",
		"internal/selfhostrunner/a_test.go": "package selfhostrunner\n",
		"selfhost/interpreter/main.rn":      "main() => 1\n",
		"selfhost/interpreter/notes.txt":    "ignored\n",
	}
	for name, content := range files {
		if err := os.WriteFile(filepath.Join(root, filepath.FromSlash(name)), []byte(content), 0o644); err != nil {
			t.Fatalf("WriteFile(%s) error = %v", name, err)
		}
	}

	first, err := selfhostDriverCacheKey(root)
	if err != nil {
		t.Fatalf("selfhostDriverCacheKey first error = %v", err)
	}
	if err := os.WriteFile(filepath.Join(root, "selfhost/interpreter/notes.txt"), []byte("still ignored\n"), 0o644); err != nil {
		t.Fatalf("WriteFile ignored file error = %v", err)
	}
	ignored, err := selfhostDriverCacheKey(root)
	if err != nil {
		t.Fatalf("selfhostDriverCacheKey ignored error = %v", err)
	}
	if ignored != first {
		t.Fatalf("cache key changed for ignored file: %s -> %s", first, ignored)
	}
	if err := os.WriteFile(filepath.Join(root, "internal/selfhostrunner/a_test.go"), []byte("package selfhostrunner\nfunc TestIgnored() {}\n"), 0o644); err != nil {
		t.Fatalf("WriteFile test file error = %v", err)
	}
	testFile, err := selfhostDriverCacheKey(root)
	if err != nil {
		t.Fatalf("selfhostDriverCacheKey test file error = %v", err)
	}
	if testFile != first {
		t.Fatalf("cache key changed for test file: %s -> %s", first, testFile)
	}
	if err := os.WriteFile(filepath.Join(root, "selfhost/interpreter/main.rn"), []byte("main() => 2\n"), 0o644); err != nil {
		t.Fatalf("WriteFile source file error = %v", err)
	}
	changed, err := selfhostDriverCacheKey(root)
	if err != nil {
		t.Fatalf("selfhostDriverCacheKey changed error = %v", err)
	}
	if changed == first {
		t.Fatalf("cache key did not change after source edit: %s", changed)
	}
}
